#ifndef REDUCTION_HPP
#define REDUCTION_HPP

#include <deque>
#include "syntax.hpp"

typedef struct stackblk {
    int state;
    AbstractSyntax      *data;
} stackblk;

typedef auto (*reduce_fun)(deque<stackblk> &) -> stackblk;

/*
#include "../syntax/syntaxDefine.hpp"

/SYN_FILE>/SYN_PROGRAM/SYN_END
/SYN_ARGS>/SYN_TYPE/SYN_ID/SYN_COMMA/SYN_ARGS
/SYN_ARGS>/SYN_TYPE/SYN_ID
/SYN_LINES>/SYN_LINE/SYN_LINES
/SYN_LINES>/SYN_LINE
/SYN_BLOCK>/SYN_LPREN/SYN_LINES/SYN_RPREN
/SYN_FUNC>/SYN_TYPE/SYN_ID/SYN_LBR/SYN_ARGS/SYN_RBR/SYN_BLOCK
/SYN_PROGRAM>/SYN_FUNC/SYN_PROGRAM
/SYN_PROGRAM>/SYN_DECL/SYN_PROGRAM
/SYN_DECL>/SYN_TYPE/SYN_ID/SYN_ENDL
/SYN_DECL>/SYN_TYPE/SYN_ID/SYN_ASSIGN/SYN_IMM/SYN_ENDL
/SYN_DEF>/SYN_TYPE/SYN_ID/SYN_ASSIGN/SYN_EXP/SYN_ENDL
/SYN_LINE>/SYN_DECL
/SYN_LINE>/SYN_DEF
/SYN_EXP>/SYN_ID/SYN_ASSIGN/SYN_EXP
/SYN_LINE>/SYN_EXP/SYN_ENDL
/SYN_CALL>/SYN_ID/SYN_LBR/SYN_EXPS/SYN_RBR
/SYN_EXPS>/SYN_EXP/SYN_COMMA/SYN_EXPS
/SYN_EXPS>/SYN_EXP
/SYN_EXP>/SYN_LBR/SYN_EXP/SYN_OP/SYN_EXP/SYN_RBR
/SYN_EXP>/SYN_ID
/SYN_EXP>/SYN_IMM
/SYN_EXP>/SYN_CALL
/SYN_PROGRAM>/SYN_DECL
/SYN_PROGRAM>/SYN_FUNC

/SYN_LINE>/SYN_IFBLK
/SYN_ELSEBLK>/SYN_ELSE/SYN_BLOCK
/SYN_ELIFBLK>/SYN_ELIF/SYN_EXP/SYN_BLOCK
/SYN_ELIFBLK>/SYN_ELIF/SYN_EXP/SYN_BLOCK/SYN_ELSEBLK
/SYN_ELIFBLK>/SYN_ELIF/SYN_EXP/SYN_BLOCK/SYN_ELIFBLK
/SYN_IFBLK>/SYN_IF/SYN_EXP/SYN_BLOCK
/SYN_IFBLK>/SYN_IF/SYN_EXP/SYN_BLOCK/SYN_ELSEBLK
/SYN_IFBLK>/SYN_IF/SYN_EXP/SYN_BLOCK/SYN_ELIFBLK

/SYN_LINE>/SYN_FORBLK
/SYN_FORBLK>/SYN_FOR/SYN_LINE/SYN_EXP/SYN_ENDL/SYN_LINE/SYN_BLOCK
/SYN_LINE>/SYN_WHILEBLK
/SYN_WHILEBLK>/SYN_WHILE/SYN_EXP/SYN_BLOCK

*/

#define ARLANG_RULES 35

extern reduce_fun reduce[];

#endif