#include "../syntax/syntaxDefine.hpp"

/SYN_FILE>/SYN_PROGRAM/SYN_END
/SYN_ARGS>/SYN_TYPE/SYN_ID/SYN_COMMA/SYN_ARGS
/SYN_ARGS>/SYN_TYPE/SYN_ID
/SYN_LINES>/SYN_LINE/SYN_LINES
/SYN_LINES>/SYN_LINE
/SYN_BLOCK>/SYN_LPREN/SYN_LINES/SYN_RPREN
/SYN_FUNC>/SYN_TYPE/SYN_ID/SYN_LBR/SYN_ARGS/SYN_RBR/SYN_BLOCK
/SYN_PROGRAM>/SYN_FUNC/SYN_PROGRAM
/SYN_PROGRAM>/SYN_DECL/SYN_PROGRAM
/SYN_DECL>/SYN_TYPE/SYN_ID/SYN_ENDL
/SYN_DECL>/SYN_TYPE/SYN_ID/SYN_ASSIGN/SYN_IMM/SYN_ENDL
/SYN_DEF>/SYN_TYPE/SYN_ID/SYN_ASSIGN/SYN_EXP/SYN_ENDL
/SYN_LINE>/SYN_DECL
/SYN_LINE>/SYN_DEF
/SYN_LINE>/SYN_ID/SYN_ASSIGN/SYN_EXP/SYN_ENDL
/SYN_LINE>/SYN_EXP/SYN_ENDL
/SYN_CALL>/SYN_ID/SYN_LBR/SYN_EXPS/SYN_RBR
/SYN_EXPS>/SYN_EXP/SYN_COMMA/SYN_EXPS
/SYN_EXPS>/SYN_EXP
/SYN_EXP>/SYN_LBR/SYN_EXP/SYN_OP/SYN_EXP/SYN_RBR
/SYN_EXP>/SYN_ID
/SYN_EXP>/SYN_IMM
/SYN_EXP>/SYN_CALL
/SYN_PROGRAM>/SYN_DECL
/SYN_PROGRAM>/SYN_FUNC



